# Site settings
author: "Val" for short.
title: What's New? 
header-img: img/home-bg.png
email: valenadelvalle4@gmail.com
copyright_name: "Val" for short.
description: > # this means to ignore newlines until "baseurl:"
  I'll tell you in a few...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leenavalena

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
