# Site settings
author: Valena Del Valle
title: My First Week of Flatiron School
header-img: img/home-bg.png
email: valenadelvalle4@gmail.com
copyright_name: Valena Del Valle
description: > # this means to ignore newlines until "baseurl:"
  What's going on in my head? 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leenavalena

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
